#!/bin/bash

set -e
pkg=fogbow-powernap

INSTALLATION_DIR="/usr/share/fogbow-powernap"
CPU_ARCH=`uname -m`
CPU_X86_64_ARCH=x86_64

adduser --system --quiet --group --disabled-password \
        --gecos "fogbow sys account" \
	--home "/var/run/fogbow" \
	fogbow || true
        
chown -R fogbow:fogbow $INSTALLATION_DIR

mkdir -p /var/run/fogbow-powernap

cd $INSTALLATION_DIR
mkdir -p lib/
cp powernap/sbin/powernapd lib/
python setup.py install
