#!/bin/bash

set -e
pkg=fogbow-manager

INSTALLATION_DIR="/usr/share/fogbow-manager"
CPU_ARCH=`uname -m`
CPU_X86_64_ARCH=x86_64
LOG_DIR="/var/log/fogbow-manager"
CONF_DIR="/etc/fogbow-manager"

adduser --system --quiet --group --disabled-password \
		--gecos "fogbow sys account" \
        --home "/var/run/fogbow" \
        fogbow || true

chown -R fogbow:fogbow $INSTALLATION_DIR

cp $INSTALLATION_DIR/fogbow-manager.example $INSTALLATION_DIR/fogbow-manager
cp $INSTALLATION_DIR/manager.conf.example $INSTALLATION_DIR/manager.conf

mkdir -p $LOG_DIR
chown -R fogbow:fogbow $LOG_DIR

ln -s $INSTALLATION_DIR/bin/fogbow-manager /usr/bin/fogbow-manager

mkdir -p $CONF_DIR
chown -R fogbow:fogbow $CONF_DIR

ln -s $INSTALLATION_DIR/log4.properties /etc/fogbow-manager/log4.properties
ln -s $INSTALLATION_DIR/manager.conf /etc/fogbow-manager/manager.conf
ln -s $INSTALLATION_DIR/contrib/upstart/fogbow-manager.conf /etc/init/fogbow-manager.conf

service fogbow-manager start