#!/bin/bash

set -e
pkg=fogbow-manager

INSTALLATION_DIR="/usr/share/fogbow-manager"
CPU_ARCH=`uname -m`
CPU_X86_64_ARCH=x86_64
LOG_DIR="/var/log/fogbow-manager"
CONF_DIR="/etc/fogbow-manager"

adduser --system --quiet --group --disabled-password \
		--gecos "fogbow sys account" \
        --home "/var/run/fogbow" \
        fogbow || true

chown -R fogbow:fogbow $INSTALLATION_DIR

if [[ ! -f $INSTALLATION_DIR/log4j.properties ]]; then
    cp $INSTALLATION_DIR/log4j.properties.example $INSTALLATION_DIR/log4j.properties
fi
if [[ ! -f $INSTALLATION_DIR/manager.conf ]]; then
    cp $INSTALLATION_DIR/manager.conf.example $INSTALLATION_DIR/manager.conf
fi

mkdir -p $LOG_DIR
chown -R fogbow:fogbow $LOG_DIR

mkdir -p $CONF_DIR
chown -R fogbow:fogbow $CONF_DIR

ln -sf $INSTALLATION_DIR/log4j.properties /etc/fogbow-manager/log4j.properties
ln -sf $INSTALLATION_DIR/manager.conf /etc/fogbow-manager/manager.conf

service fogbow-manager start
