#!/bin/bash

set -e
pkg=fogbow-voms-clients-wrapper

INSTALLATION_DIR="/usr/share/fogbow-voms-clients-wrapper"
CPU_ARCH=`uname -m`
CPU_X86_64_ARCH=x86_64

chown -R fogbow:fogbow $INSTALLATION_DIR
if [ -f /usr/bin/voms-proxy-init ]; then
    if ! [ -f /usr/bin/voms-proxy-init-helper ]; then
        cp /usr/bin/voms-proxy-init /usr/bin/voms-proxy-init-helper
    fi
    rm /usr/bin/voms-proxy-init
    ln -sf $INSTALLATION_DIR/bin/fogbow-voms-proxy-normalizer /usr/bin/voms-proxy-init
    chmod +x /usr/bin/voms-proxy-init
fi
