#!/bin/bash

set -e
pkg=fogbow-reverse-tunnel

INSTALLATION_DIR="/usr/share/fogbow-reverse-tunnel"
CPU_ARCH=`uname -m`
CPU_X86_64_ARCH=x86_64
LOG_DIR="/var/log/fogbow-reverse-tunnel"
CONF_DIR="/etc/fogbow-reverse-tunnel"

adduser --system --quiet --group --disabled-password \
	    --gecos "fogbow sys account" \
        --home "/var/run/fogbow" \
        fogbow || true
        
chown -R fogbow:fogbow $INSTALLATION_DIR

cp $INSTALLATION_DIR/log4j.properties.example $INSTALLATION_DIR/log4j.properties
cp $INSTALLATION_DIR/reverse-tunnel.conf.example $INSTALLATION_DIR/reverse-tunnel.conf

mkdir -p $LOG_DIR
chown -R fogbow:fogbow $LOG_DIR

mkdir -p $CONF_DIR
chown -R fogbow:fogbow $CONF_DIR

ln -sf $INSTALLATION_DIR/log4.properties /etc/fogbow-reverse-tunnel/log4.properties
ln -sf $INSTALLATION_DIR/reverse-tunnel.conf /etc/fogbow-reverse-tunnel/reverse-tunnel.conf

service fogbow-reverse-tunnel start
